CREATE DATABASE BHDT
GO
USE BHDT
GO
-- Tạo bảng Nhân Viên 
CREATE TABLE NHANVIEN(
MANV VARCHAR(10) PRIMARY KEY NOT NULL,
TENNV NVARCHAR(50) NOT NULL,
TENCV NVARCHAR(50) NOT NULL,
MACV VARCHAR(10) NOT NULL,
DIENTHOAI NVARCHAR(50) NOT NULL,
DIACHI NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR (50) NOT NULL,
GIOITINH INT NOT NULL,
TENDANGNHAP NVaRCHAR (50) NOT NULL,
MATKHAU NVARCHAR (50) NOT NULL
)
-- Tạo bảng Chức vụ 
CREATE TABLE CHUCVU(
MACV VARCHAR(10) PRIMARY KEY NOT NULL,
TENCV NVARCHAR(50) NOT NULL,
MANV VARCHAR(10)NOT NULL)

-- Tạo bảng SanPham 
CREATE TABLE SANPHAM(
MASP VARCHAR(10)PRIMARY KEY NOT NULL,
TENSP NVARCHAR(50) NOT NULL,
MALOAISP VARCHAR(10) NOT NULL,
TENLOAI NVARCHAR(50) NOT NULL, 
MANSX VARCHAR(10) NOT NULL,
TENNSX NVARCHAR (50)  NOT NULL,  
GIA INT NOT NULL, 
HINHANH IMAGE NOT NULL,
KICHTHUOC INT NOT NULL, 
NGAYSX DATETIME NOT NULL, 
CPU NVARCHAR (50) NOT NULL, 
RAM NVARCHAR (50) NOT NULL, 
HDH NVARCHAR (50) NOT NULL,
MOTA NTEXT NOT NULL,
MAU NVARCHAR (50) NOT NULL
)
-- Tạo bảng Loại Sản Phẩm 
CREATE TABLE LOAISANPHAM(
MALOAISP VARCHAR(10) PRIMARY KEY NOT NULL,
TENLOAI NVARCHAR(50) NOT NULL,
)
-- Tạo bảng Nhà sản xuất 
CREATE TABLE NHASX(
MANSX VARCHAR(10)PRIMARY KEY NOT NULL,
TENNSX NVARCHAR (50)  NOT NULL,
DIACHI NVARCHAR(50) NOT NULL,
DIENTHOAI NVARCHAR(50) NOT NULL,
)
-- Tạo bảng Khách hàng 
CREATE TABLE KHACHHANG(
MAKH VARCHAR(10) PRIMARY KEY NOT NULL,
TENNKH NVARCHAR(50) NOT NULL,
DIENTHOAI NVARCHAR(50) NULL,
DIACHI NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR (50) NOT NULL,
GIOITINH NVARCHAR(3) NOT NULL, 
TENDANGNHAP NVARCHAR (50) NOT NULL,
MATKHAU NVARCHAR (50) NOT NULL,
NGAYSINH DATE NOT NULL,
)
-- Tạo bảng Hóa đơn đặt 
CREATE TABLE HOADONDAT
(
MAHHD VARCHAR(10) PRIMARY KEY NOT NULL,
MASP VARCHAR (10) NOT NULL,
MAKH VARCHAR(10) NOT NULL, 
TENKH VARCHAR (10) NOT NULL, 
TENSP NVARCHAR(50) NOT NULL,
SOLUONGMUA INT NOT NULL,
DONGIA INT NOT NULL, 
DIACHINHAN NVARCHAR(50) NOT NULL, 
)
-- Tạo bảng Hóa đơn xuất 
CREATE TABLE HOADONXUAT
( 
MAHDX VARCHAR(10) PRIMARY KEY NOT NULL,
NGAYGIAODICH DATETIME NOT NULL, 
MASP VARCHAR(10) NOT NULL ,
SOLUONG INT NOT NULL 
)
-- Tạo bảng Hóa đơn giao 
CREATE TABLE HOADONGIAO 
(
MAHDGIAO VARCHAR(10) PRIMARY KEY NOT NULL,
TENSP  VARCHAR (10) NOT NULL,
MASP VARCHAR (10) NOT NULL,
MAKH VARCHAR(10) NOT NULL,
TENNKH NVARCHAR(50) NOT NULL,
NGAYGIAO DATETIME NOT NULL, 
TONGTIEN INT NOT NULL
)
-- Tạo bảng Hóa đơn nhập hàng 
CREATE TABLE HOADONNHAP
(
MAHDNHAP VARCHAR(10) PRIMARY KEY NOT NULL,
MANSX VARCHAR(10) NOT NULL, 
MASP VARCHAR(10) NOT NULL, 
SOLUONGNHAP INT NOT NULL, 
NGAYNHAP DATETIME NOT NULL, 
TONGTIEN INT NOT NULL, 
TINHTRANGHD NVARCHAR(10) NOT NULL) 

-- Tạo bảng Kho 
CREATE TABLE KHO 
( 
MAKHO VARCHAR(10) PRIMARY KEY NOT NULL,
MASP VARCHAR(10) NOT NULL,
NGAYNHAP DATETIME NOT NULL, 
NGAYXUAT DATETIME NOT NULL, 
TRANGTHAI NVARCHAR(10) NOT NULL) 
-- Tạo bảng Bảng thống kê 
CREATE TABLE BANGTHONGKE
( 
SoDHDat INT PRIMARY KEY NOT NULL,
SOHDNHAP INT NOT NULL,
SPBanChay INT NOT NULL, 
DOANHTHU INT  NOT NULL, 
) 
-- Tạo khóa ngoại cho bảng Nhân viên 
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_CV FOREIGN KEY(MACV) REFERENCES CHUCVU(MACV) 
--Tạo khóa ngoại cho bảng sản phẩm
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP_LSP FOREIGN KEY(MALOAISP) REFERENCES LOAISANPHAM(MALOAISP)
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP_NSX FOREIGN KEY(MANSX) REFERENCES NHASX(MANSX)
--Tạo khóa ngoại cho bảng KHO
ALTER TABLE KHO ADD CONSTRAINT FK_K_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
-- Tạo khóa ngoại cho bảng hoá đơn đặt 
ALTER TABLE HOADONDAT ADD CONSTRAINT FK_HDD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) 
ALTER TABLE HOADONDAT ADD CONSTRAINT FK_HDD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) 
-- Tạo khoá ngoại cho bản hoá đơn xuất 
ALTER TABLE HOADONXUAT ADD CONSTRAINT FK_HDX_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
-- Tạo khoá ngoại cho bản hoá đơn giao 
ALTER TABLE HOADONGIAO ADD CONSTRAINT FK_HDG_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
ALTER TABLE HOADONGIAO ADD CONSTRAINT FK_HDG_HK FOREIGN KEY (MAHK) REFERENCES KHACHHANG(MAKH) 
-- Tạo khóa ngoại cho bảng Hóa đơn nhập 
ALTER TABLE HOADONNHAP ADD CONSTRAINT  FK_HDN_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) 
ALTER TABLE HOADONNHAP ADD CONSTRAINT  FK_HDN_NSX FOREIGN KEY(MANSX) REFERENCES NHASX(MANSX)






 
